name: "Build Executable"

on:
  # Inputs the workflow accepts.
  inputs:
    release-description:
      # Friendly description to be shown in the UI instead of 'name'
      description: 'Release Description'
      # Default value if no value is explicitly provided
      default: 'Default Value'
      # Input has to be provided for the workflow to run
      required: false
      # The data type of the input
      type: string
    release-tag:
      # Friendly description to be shown in the UI instead of 'name'
      description: 'Release Tag'
      # Default value if no value is explicitly provided
      default: 'V.0.0.0'
      # Input has to be provided for the workflow to run
      required: false
      # The data type of the input
      type: string



defaults:
  run:
    shell: bash

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        python-version:
          - "3.12"

    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Install Project Libraries"
        run: |
          python -m pip install -r requirements.txt

      - name: "Run Build Script"
        run: |
          cd "Batch Files"
          ./build.bat
          cd ..

      - name: copy build to build folder (windows)
        if: matrix.platform == 'windows-latest'
        run: | 
          cd ./_PYINSTALLER/dist
          robocopy "../build" "./dist/" /MIR
          if ($lastexitcode -lt 8) { $global:LASTEXITCODE = $null }
          cd ..
          Compress-Archive ./build ./build.zip

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.release-tag }}
          release_name: ${{ github.event.inputs.release-tag }}
          body: |
            ${{ github.event.inputs.release-description }}
            Release Generated by github action script
          draft: true
          prerelease: false

      - name: Upload Release Asset (windows)
        if: matrix.platform == 'windows-latest'  # This must match the platform value defined above.
        id: upload-release-asset-windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: build.zip
          asset_name: build.zip
          asset_content_type: application/zip
